version: '3'
services:
    sgws:
       build:
         context: ./deployment
         dockerfile: Dockerfile
       image: sgws
       ports:
         - "8080:8080"
       environment:
         - FLASK_DEBUG=1