version: '3'
services:
   sgws:
       build:
         context: ./deployment
         dockerfile: Dockerfile
      image: sgws
       volumes:
         - "./storage_grid:/opt/repo/storage_grid"
       command: ["nosetests", "--with-xunit","--xunit-file=./tests/nosetests.xml" ,"--with-coverage", "--cover-html" ,"--cover-html-dir=./tests/htmlcov", "--cover-xml","--cover-xml-file=./tests/coverage.xml"]
