version: '3'
services:
    sgws:
       build:
         context: .
         dockerfile: Dockerfile
       image: kannan1985/sgws
       user: "1001"
       ports:
         - "8080:8080"
       environment:
         - FLASK_DEBUG=1
