apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgws-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
        component: sgwsk8
  template:
     metadata:
        labels:
           component: sgwsk8
     spec:
        containers:
          - name: sgws
            image: kannan1985/sgws
            user: "1001"
            ports:
              - containerPort: 8080
