version: '3'
services:
    sgws:
       build:
         context: .
         dockerfile: Dockerfile
       image: sgws
       ports:
         - "8081:8080"
       environment:
         - FLASK_DEBUG=1
