apiVersion: v1
kind: Service
metadata:
  name: {{ include "sghelm.fullname" . }}
  labels:
    {{- include "sghelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "sghelm.selectorLabels" . | nindent 4 }}
