{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sghelm.serviceAccountName" . }}
  labels:
{{ include "sghelm.labels" . | nindent 4 }}
{{- end -}}
